/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.ControllercadastroCliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model_Bean.ModelcadastroCliente;

/**
 *
 * @author Edson Come
 */
public class CClientes extends javax.swing.JFrame {
    
    ControllercadastroCliente controllercadastroCliente = new ControllercadastroCliente();
    ModelcadastroCliente modelcadastroCliente = new ModelcadastroCliente();
    ArrayList<ModelcadastroCliente> listaModelCliente = new ArrayList<>();
    String editarSalvar;
    
    /**
     * Creates new form CClientes
     */
    public CClientes() {
        initComponents();
        setLocationRelativeTo(null);
         carregarCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldContacto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jButtonNovo = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonCanselar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo:");

        jTextFieldCodigo.setEnabled(false);

        jLabel2.setText("Nome do Cliente:");

        jLabel3.setText("Endereco:");

        jLabel4.setText("Bairro:");

        jLabel5.setText("Cidade:");

        jLabel6.setText("Contacto:");

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Cidade", "Contacto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableClientes);
        if (jTableClientes.getColumnModel().getColumnCount() > 0) {
            jTableClientes.getColumnModel().getColumn(0).setMinWidth(70);
            jTableClientes.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTableClientes.getColumnModel().getColumn(0).setMaxWidth(70);
            jTableClientes.getColumnModel().getColumn(2).setMinWidth(90);
            jTableClientes.getColumnModel().getColumn(2).setPreferredWidth(90);
            jTableClientes.getColumnModel().getColumn(2).setMaxWidth(90);
            jTableClientes.getColumnModel().getColumn(3).setMinWidth(90);
            jTableClientes.getColumnModel().getColumn(3).setPreferredWidth(90);
            jTableClientes.getColumnModel().getColumn(3).setMaxWidth(90);
        }

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/new.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jButtonCanselar.setText("Canselar");
        jButtonCanselar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCanselarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(114, 114, 114)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(161, 161, 161)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 81, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConfirmar)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonCanselar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNome)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonConfirmar)
                    .addComponent(jButtonCanselar)
                    .addComponent(jButtonExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // Metodo para salvar cliente
        
        
         
         if (editarSalvar.equals("salvar")){
        modelcadastroCliente.setNome_Cliente(this.jTextFieldNome.getText());
        modelcadastroCliente.setEndereco_cliente(this.jTextFieldEndereco.getText());
        modelcadastroCliente.setBairro_cliente(this.jTextFieldBairro.getText());
        modelcadastroCliente.setCidade_cliente(this.jTextFieldCidade.getText());
        modelcadastroCliente.setTelefone_cliente(Integer.parseInt(jTextFieldContacto.getText()));
             
             if(controllercadastroCliente.salvarcadastroClienteController(modelcadastroCliente)>0){
            JOptionPane.showMessageDialog (this, " Dados gravados com sucesso "," Atencao ", JOptionPane.WARNING_MESSAGE);
            //Colocar os clientes na tabela
            carregarCliente();
            limparCampos();
        }else{
            JOptionPane.showMessageDialog (this, " Erro ao gravar os dados "," Erro ", JOptionPane.ERROR_MESSAGE);
        }    
         }else{
        modelcadastroCliente.setId_Cliente(Integer.parseInt(this.jTextFieldCodigo.getText()));
        modelcadastroCliente.setNome_Cliente(this.jTextFieldNome.getText());
        modelcadastroCliente.setEndereco_cliente(this.jTextFieldEndereco.getText());
        modelcadastroCliente.setBairro_cliente(this.jTextFieldBairro.getText());
        modelcadastroCliente.setCidade_cliente(this.jTextFieldCidade.getText());
        modelcadastroCliente.setTelefone_cliente(Integer.parseInt(jTextFieldContacto.getText()));
             
             if(controllercadastroCliente.atualizarcadastroClienteController(modelcadastroCliente)){
            JOptionPane.showMessageDialog (this, " Dados alterados com sucesso "," Atencao ", JOptionPane.WARNING_MESSAGE);
            //Colocar os clientes na tabela
            carregarCliente();
            limparCampos();
        }else{
            JOptionPane.showMessageDialog (this, " Erro ao alterar os dados "," Erro ", JOptionPane.ERROR_MESSAGE);
        }   
             
         } 
        
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // Metodo para excluir cliente
        int linha = jTableClientes.getSelectedRow();
        int codigoCliente = (int) jTableClientes.getValueAt(linha, 0);
        if(controllercadastroCliente.excluircadastroClienteController(codigoCliente)){
         JOptionPane.showMessageDialog (this, " Cliente excluido com sucesso "," Atencao ", JOptionPane.WARNING_MESSAGE); 
         this.carregarCliente();
        }else{
          JOptionPane.showMessageDialog (this, " Erro ao excluir o Cliente "," Erro ", JOptionPane.ERROR_MESSAGE);   
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // Boatao que confirma a alteracao de dados
        int linha = jTableClientes.getSelectedRow();
        int codigo = (int) jTableClientes.getValueAt(linha, 0);
        editarSalvar = "alterar";
        modelcadastroCliente = controllercadastroCliente.getcadastroClienteController(codigo);
        jTextFieldCodigo.setText(String.valueOf(modelcadastroCliente.getId_Cliente()));
        jTextFieldNome.setText(modelcadastroCliente.getNome_Cliente());
        jTextFieldEndereco.setText(modelcadastroCliente.getEndereco_cliente());
        jTextFieldBairro.setText(modelcadastroCliente.getBairro_cliente());
        jTextFieldCidade.setText(modelcadastroCliente.getCidade_cliente());
        jTextFieldContacto.setText(String.valueOf(modelcadastroCliente.getTelefone_cliente()));
        
        habilitarDesabilitarCampos(true);
              
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // Botao para salvar novos dados
         limparCampos();
        habilitarDesabilitarCampos(true);
        editarSalvar = "salvar";
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCanselarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCanselarActionPerformed
        // Botao para canselar o registro
        limparCampos();
        habilitarDesabilitarCampos(false);
    }//GEN-LAST:event_jButtonCanselarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CClientes().setVisible(true);
            }
        });
    }
    
     private void habilitarDesabilitarCampos(boolean condicao){
       jTextFieldCidade.setEnabled(condicao);
       jTextFieldNome.setEnabled(condicao);
       jTextFieldBairro.setEnabled(condicao);
       jTextFieldEndereco.setEnabled(condicao);
       jTextFieldContacto.setEnabled(condicao);
       jButtonConfirmar.setEnabled(condicao);
       
    }
      private void limparCampos(){
      jTextFieldCodigo.setText("");
      jTextFieldNome.setText("");
      jTextFieldBairro.setText("");
      jTextFieldEndereco.setText("");
      jTextFieldCidade.setText("");
      jTextFieldContacto.setText("");
      
    }
    
    private void carregarCliente(){
        listaModelCliente = controllercadastroCliente.getListacadastroClienteController();
        DefaultTableModel modelo = (DefaultTableModel)jTableClientes.getModel();
        modelo.setNumRows(0);
        int cont = listaModelCliente.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelCliente.get(i).getId_Cliente(),
                listaModelCliente.get(i).getNome_Cliente(),
                listaModelCliente.get(i).getCidade_cliente(),
                listaModelCliente.get(i).getTelefone_cliente()
            });
            
        }
            
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCanselar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldContacto;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
