/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerVendasCliente;
import UTIL.BLDatas;
import controller.ControllerCProduto;
import controller.ControllerVenda;
import controller.ControllerVendasProdutos;
import controller.ControllercadastroCliente;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model_Bean.ModelCProduto;
import model_Bean.ModelVendasProdutos;
import model_Bean.ModelVenda;
import model_Bean.ModelVendaCliente;
import model_Bean.ModelcadastroCliente;

/**
 *
 * @author Edson Come
 */
public class viewVendas extends javax.swing.JFrame {
    ControllercadastroCliente controllercadastroCliente = new ControllercadastroCliente();
    ModelcadastroCliente modelcadastroCliente = new ModelcadastroCliente();
    ArrayList<ModelcadastroCliente> listaModelCliente = new ArrayList<>();
    
    ControllerCProduto controllerCProduto = new ControllerCProduto();
    ModelCProduto modelCProduto = new ModelCProduto();
    ArrayList<ModelCProduto> listaModelCProduto = new ArrayList<>();
    ArrayList<ModelVendaCliente> listaModelVendaCliente = new ArrayList<>();
    ControllerVendasCliente controllerVendasCliente = new ControllerVendasCliente();
    ControllerVenda controllerVendas = new ControllerVenda(); 
    ModelVenda modelVenda = new ModelVenda();
    BLDatas blDatas = new BLDatas();
    ControllerVendasProdutos controllerVendasProdutos = new ControllerVendasProdutos();
    ModelVendasProdutos modelVendasProdutos = new ModelVendasProdutos();
    ArrayList<ModelVendasProdutos> listaModelVendasProdutos = new ArrayList<>();
    String alterarSalvar;
    

    /**
     * Creates new form viewVendas
     */
    public viewVendas() {
        initComponents();
        listarCliente();
        listarProdutos();
        carregarVendas();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JComboBoxNCliente = new componentes.UJComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNrVenda = new javax.swing.JTextField();
        jTextCProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JComboBoxNProduto = new componentes.UJComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jButtonAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePVendas = new javax.swing.JTable();
        jButtonNovo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDesconto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jButtonCanselar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonExcluirPro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTFPesquisa = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVendas = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo Cliente:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, -1));

        jTextFieldCodigo.setEnabled(false);
        jTextFieldCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCodigoFocusLost(evt);
            }
        });
        jTextFieldCodigo.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jTextFieldCodigoMouseWheelMoved(evt);
            }
        });
        jPanel1.add(jTextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 79, -1));

        jLabel2.setText("Nome do cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 11, -1, -1));

        JComboBoxNCliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                JComboBoxNClientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(JComboBoxNCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 31, 233, -1));

        jLabel3.setText("Nr da venda:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 11, -1, -1));

        jTextFieldNrVenda.setEnabled(false);
        jPanel1.add(jTextFieldNrVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 31, 130, -1));

        jTextCProduto.setEnabled(false);
        jTextCProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextCProdutoFocusLost(evt);
            }
        });
        jPanel1.add(jTextCProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 91, 79, -1));

        jLabel4.setText("Cod. Produto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 69, -1, -1));

        jLabel5.setText("Nome do Produto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 69, -1, -1));

        JComboBoxNProduto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                JComboBoxNProdutoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(JComboBoxNProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 91, 233, -1));

        jLabel6.setText("Quantidade:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 69, -1, -1));
        jPanel1.add(jTextFieldQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 91, 124, -1));

        jButtonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 89, -1, -1));

        jTablePVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.Produto", "Nome Produto", "Quant.", "Valor Un.", "Volor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePVendas);
        if (jTablePVendas.getColumnModel().getColumnCount() > 0) {
            jTablePVendas.getColumnModel().getColumn(0).setMinWidth(90);
            jTablePVendas.getColumnModel().getColumn(0).setPreferredWidth(90);
            jTablePVendas.getColumnModel().getColumn(0).setMaxWidth(90);
            jTablePVendas.getColumnModel().getColumn(2).setMinWidth(70);
            jTablePVendas.getColumnModel().getColumn(2).setPreferredWidth(70);
            jTablePVendas.getColumnModel().getColumn(2).setMaxWidth(70);
            jTablePVendas.getColumnModel().getColumn(3).setMinWidth(70);
            jTablePVendas.getColumnModel().getColumn(3).setPreferredWidth(70);
            jTablePVendas.getColumnModel().getColumn(3).setMaxWidth(70);
            jTablePVendas.getColumnModel().getColumn(4).setMinWidth(70);
            jTablePVendas.getColumnModel().getColumn(4).setPreferredWidth(70);
            jTablePVendas.getColumnModel().getColumn(4).setMaxWidth(70);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 583, 171));

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/new.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 353, -1, -1));

        jLabel7.setText("Desconto:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 307, -1, -1));

        jTextFieldDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDescontoFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 327, 77, -1));

        jLabel8.setText("Valor total:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 307, -1, -1));
        jPanel1.add(jTextFieldValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 327, 90, -1));

        jButtonCanselar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel.png"))); // NOI18N
        jButtonCanselar.setText("Canselar");
        jPanel1.add(jButtonCanselar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 357, -1, -1));

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 362, -1, -1));

        jButtonExcluirPro.setText("Excluir");
        jButtonExcluirPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirProActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluirPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jLabel9.setText("Pesquisa:");

        jButtonPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search_2.png"))); // NOI18N

        jTableVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome Cliente", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableVendas);
        if (jTableVendas.getColumnModel().getColumnCount() > 0) {
            jTableVendas.getColumnModel().getColumn(0).setMinWidth(100);
            jTableVendas.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTableVendas.getColumnModel().getColumn(0).setMaxWidth(100);
            jTableVendas.getColumnModel().getColumn(2).setMinWidth(110);
            jTableVendas.getColumnModel().getColumn(2).setPreferredWidth(110);
            jTableVendas.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTFPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButtonEditar)))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesquisa)
                    .addComponent(jTFPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonEditar))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Consultar/Excluir/Alterar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCodigoFocusLost
        // Metodo para preecher o nome do cliente atravaz do seu codigo
        modelcadastroCliente = controllercadastroCliente.getcadastroClienteController(Integer.parseInt(jTextFieldCodigo.getText()));
        JComboBoxNCliente.setSelectedItem(modelcadastroCliente.getNome_Cliente());
    }//GEN-LAST:event_jTextFieldCodigoFocusLost

    private void JComboBoxNClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_JComboBoxNClientePopupMenuWillBecomeInvisible
        // Metodo para preecher o codigo do cliente atravaz do seu nome
        if(JComboBoxNCliente.isPopupVisible()){
          modelcadastroCliente = controllercadastroCliente.getcadastroClienteController(JComboBoxNCliente.getSelectedItem().toString()); 
          jTextFieldCodigo.setText(String.valueOf(modelcadastroCliente.getId_Cliente()));
        }
    }//GEN-LAST:event_JComboBoxNClientePopupMenuWillBecomeInvisible

    private void JComboBoxNProdutoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_JComboBoxNProdutoPopupMenuWillBecomeInvisible
        // Metodo para preecher o codigo do produto atravaz do seu nome do produto
        if (JComboBoxNProduto.isPopupVisible()){
            modelCProduto = controllerCProduto.getCProdutoController(JComboBoxNProduto.getSelectedItem().toString());
            jTextCProduto.setText(String.valueOf(modelCProduto.getId()));
            
        }
    }//GEN-LAST:event_JComboBoxNProdutoPopupMenuWillBecomeInvisible

    private void jTextCProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextCProdutoFocusLost
        // Metodo para preecher o nome do produto atravaz do seu codigo
        modelCProduto = controllerCProduto.getCProdutoController(Integer.parseInt(jTextCProduto.getText()));
        JComboBoxNProduto.setSelectedItem(modelCProduto.getNome());
    }//GEN-LAST:event_jTextCProdutoFocusLost

    private void jTextFieldCodigoMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jTextFieldCodigoMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoMouseWheelMoved

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        // Adiciona Produtos
        if(jTextFieldQuantidade.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Preeche todos os campos"," Atencao ", JOptionPane.WARNING_MESSAGE);
        }else{
         modelCProduto = controllerCProduto.getCProdutoController(Integer.parseInt(jTextFieldCodigo.getText()));
         DefaultTableModel model = (DefaultTableModel) jTablePVendas.getModel();
         int cont = 0;
         double quantidade = 0;
         quantidade = Double.parseDouble(jTextFieldQuantidade.getText());
         
            for (int i = 0; i < cont; i++) {
                model.setNumRows(0);
            }
                model.addRow(new Object[]{
                    modelCProduto.getId(),
                    modelCProduto.getNome(),
                    jTextFieldQuantidade.getText(),
                    modelCProduto.getValor(),
                    quantidade * modelCProduto.getValor()
                });
                somarValorTotalProduto();
        }
        
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jTextFieldDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDescontoFocusLost
        // Metodo de calcular o desconto
        somarValorTotalProduto();
    }//GEN-LAST:event_jTextFieldDescontoFocusLost

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // Metodo para fazer nova venda
        alterarSalvar = "novo";
        limparFormulario();
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // Confirmar as vendas
        int codigoVenda = 0, codigoProduto=0;
        double desconto =0;
        listaModelVendasProdutos = new ArrayList<>();
        if(jTextFieldDesconto.getText().equals("")){
             desconto = 0;
        }else{
             desconto = Double.parseDouble(jTextFieldDesconto.getText());
        }
        
        modelVenda.setCliente(Integer.parseInt(jTextFieldCodigo.getText()));
        try {
            modelVenda.setVenDataVenda(blDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception ex) {
        }
        modelVenda.setVendaValorLiquido(Double.parseDouble(jTextFieldValorTotal.getText()));
        modelVenda.setVendaValorProduto(Double.parseDouble(jTextFieldValorTotal.getText()) + desconto);
     
           modelVenda.setVenDesconto(0);
       
           modelVenda.setVenDesconto(desconto); 
        
        
        // Salva a venda
        codigoVenda = controllerVendas.salvarVendaController(modelVenda);
        if(codigoVenda>0){
          JOptionPane.showMessageDialog (this, " Dados gravados com sucesso "," Atencao ", JOptionPane.WARNING_MESSAGE);  
          
        }else{
           JOptionPane.showMessageDialog (this, " Erro ao gravar os dados "," Erro ", JOptionPane.ERROR_MESSAGE); 
        }
        int cont = jTablePVendas.getRowCount();
        for (int i = 0; i < cont; i++) {
            codigoProduto = (int) jTablePVendas.getValueAt(i, 0);
            modelVendasProdutos = new ModelVendasProdutos();
            modelCProduto = new ModelCProduto();
            modelVendasProdutos.setProduto((codigoProduto));
            modelVendasProdutos.setVendas(codigoVenda);
            modelVendasProdutos.setVenProValor((double) jTablePVendas.getValueAt(i, 3));
            modelVendasProdutos.setVenProQuantidade(Integer.parseInt(jTablePVendas.getValueAt(i, 2).toString()));
            //Produto
            modelCProduto.setId((codigoProduto));
            modelCProduto.setQuant(controllerCProduto.getCProdutoController(codigoProduto).getQuant()
                    - Integer.parseInt(jTablePVendas.getValueAt(i, 2).toString()));
            listaModelCProduto.add(modelCProduto);
            
            listaModelVendasProdutos.add(modelVendasProdutos);
        }
        //Salvar os produtos da venda
        if(controllerVendasProdutos.salvarVendasProdutosController(listaModelVendasProdutos)){
            //Alterar o stock de produtos
            controllerCProduto.alterarStockCProdutoController(listaModelCProduto);
           JOptionPane.showMessageDialog (this, " Dados gravados com sucesso "," Atencao ", JOptionPane.WARNING_MESSAGE); 
           carregarVendas();
           limparFormulario();
        }else{
           JOptionPane.showMessageDialog (this, " Erro ao gravar os dados "," Erro ", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonExcluirProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirProActionPerformed
     // Metodo para excluir um produto adicionado na tabela
        int linha = jTablePVendas.getSelectedRow();
        int codigo = (int) jTablePVendas.getValueAt(linha, 0);
        
        if(controllerVendas.excluirVendaController(codigo)){
         JOptionPane.showMessageDialog (this, " Dados gravados com sucesso "," Atencao ", JOptionPane.WARNING_MESSAGE); 
         carregarVendas();
        }else{
        JOptionPane.showMessageDialog (this, " Erro ao gravar os dados "," Erro ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonExcluirProActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // Metodo para excluir um registro de venda
        int linha = jTableVendas.getSelectedRow();
        int codigo = (int) jTableVendas.getValueAt(linha, 0);

        if(controllerVendas.excluirVendaController(codigo)){
            JOptionPane.showMessageDialog (this, " Dados gravados com sucesso "," Atencao ", JOptionPane.WARNING_MESSAGE);
            carregarVendas();
        }else{
            JOptionPane.showMessageDialog (this, " Erro ao gravar os dados "," Erro ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // Metodo para editar uma venda
        alterarSalvar = "alterar";
        int linha = jTableVendas.getSelectedRow();
        int codigoVenda = (int) jTableVendas.getValueAt(linha, 0);
        //listaModelVendasProdutos = controllerVendasProdutos.getListaVendasProdutosController(codigoVenda);
        DefaultTableModel modelo = (DefaultTableModel) jTablePVendas.getModel();
        modelo.setNumRows(0);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewVendas().setVisible(true);
            }
        });
    }
    
    private void preencheCodigoProdutoComboBox(){
        
    }
    /**
     * Preeche o ComboBox com todos clientes
     */
    private void listarCliente(){
     listaModelCliente = controllercadastroCliente.getListacadastroClienteController();
     JComboBoxNCliente.removeAllItems();
        for (int i = 0; i < listaModelCliente.size(); i++) {
         JComboBoxNCliente.addItem(listaModelCliente.get(i).getNome_Cliente());
        }
    }
    /**
     * Preeche o ComboBox com todos Produtos
     */
    private void listarProdutos(){
        listaModelCProduto = controllerCProduto.getListaCProdutoController();
        JComboBoxNProduto.removeAllItems();
        for (int i = 0; i < listaModelCliente.size(); i++) {
         JComboBoxNProduto.addItem(listaModelCProduto.get(i).getNome());
        }
    }
    /**
     * Metodo de aplicar desconto
     */
    private void aplicarDesconto(){
        try {
              jTextFieldValorTotal.setText(String.valueOf(
              Double.parseDouble(jTextFieldValorTotal.getText()) - Double.parseDouble(jTextFieldDesconto.getText())));  
        } catch (NumberFormatException e) {
        }
        
        
    }
    /**
     * Metodo de somar o valor total de produto
     */
    private void somarValorTotalProduto(){
        double soma=0, valor;
        int cont = jTablePVendas.getRowCount();
        for (int i = 0; i < cont; i++) {
            valor = (double) jTablePVendas.getValueAt(i, 4);
            soma = soma + valor;
            jTextFieldValorTotal.setText(String.valueOf(soma));
            aplicarDesconto();
        }
        
    }
    /**
     * Carregar Vendas
     */
    private void carregarVendas(){
        DefaultTableModel modelo = (DefaultTableModel) jTableVendas.getModel();
        listaModelVendaCliente = controllerVendasCliente.getListaVendaClienteController();
        int cont = listaModelVendaCliente.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
            listaModelVendaCliente.get(i).getModelVenda().getIdVenda(),
            listaModelVendaCliente.get(i).getModelcadastroCliente().getNome_Cliente(),
            listaModelVendaCliente.get(i).getModelVenda().getVenDataVenda()
                    }); 
        }
    }
    private void carregarListaProduto(){
        DefaultTableModel modelo = (DefaultTableModel) jTablePVendas.getModel();
        listaModelVendaCliente = controllerVendasCliente.getListaVendaClienteController();
        int cont = listaModelVendaCliente.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
            listaModelVendaCliente.get(i).getModelVenda().getIdVenda(),
            listaModelVendaCliente.get(i).getModelcadastroCliente().getNome_Cliente(),
            listaModelVendaCliente.get(i).getModelVenda().getVenDataVenda()
                    }); 
        }
    }
    /**
     * Metodo para limpar o formulario de venda
     */
    private void limparFormulario(){
        jTextFieldDesconto.setText("");
        jTextFieldValorTotal.setText("");
        jTextFieldQuantidade.setText("");
         DefaultTableModel modelo = (DefaultTableModel) jTablePVendas.getModel();
         modelo.setNumRows(0);
         
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.UJComboBox JComboBoxNCliente;
    private componentes.UJComboBox JComboBoxNProduto;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonCanselar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonExcluirPro;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFPesquisa;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablePVendas;
    private javax.swing.JTable jTableVendas;
    private javax.swing.JTextField jTextCProduto;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDesconto;
    private javax.swing.JTextField jTextFieldNrVenda;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JTextField jTextFieldValorTotal;
    // End of variables declaration//GEN-END:variables
}
